name: carpi-site-dev-environment

services:
  site:
    build: .
    image: carpi-site:latest
    container_name: carpi-site
    # Ensure image is built locally and is not pulled from a registry
    pull_policy: build
    restart: on-failure
    # Enable interactive mode to allow scraper command input and output
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"
    # Mount local code over the code built into the container for automatic
    # reloading during development.
    volumes:
      - .:/site
      - /site/node_modules
