services:
  web:
    build: .
    image: carpi:latest
    container_name: carpi

    # expose port 5173
    ports:
      - "5173:5173"

    # mount the current directory to /app in the container
    volumes:
      - .:/app
      - /app/node_modules

    # interactive terminal
    stdin_open: true
    tty: true
